ALTER INDEX [PK__tmp_ms_x__737584F76438332E] ON [dbo].[Images] REBUILD PARTITION = ALL WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
DBCC SHRINKDATABASE(N'D:\USERS\MURAD\DOCUMENTS\SDB\DB\IMAGES.MDF' )
UPDATE Images SET Sim = 0.0;
UPDATE Images SET Descriptors = 0x;
UPDATE Images SET Stars = 0;
UPDATE Images SET Node = '';